### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by andress134** [aw1875/puppeteer-hcaptcha#1]
Hello sir @aw1875 , im testing your repo, but some wrong

```js
(node:24149) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'src' of null
    at <anonymous>:5:6
    at ExecutionContext._evaluateInternal (/root/solver/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/root/solver/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async hcaptcha (/root/solver/node_modules/puppeteer-hcaptcha/hcaptcha.js:130:3)
    at async /root/solver/test.js:26:5
(node:24149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
What is wrong?

**Comment by aw1875** [comment]
Do you mind sharing your code for context?

**Comment by andress134** [comment]
I have a golang script, that call to this lib to bypass hcaptcha
Calling to your repo, get the hcaptcha answer, and return it on my golang script
here is my exemple golang script

```js
driver := agouti.ChromeDriver(
	    agouti.ChromeOptions("args", []string{
	  `--window-size=600,1000`,
          "--headless",
          "--window-position=000,000",
          "--disable-dev-shm-usage",
          "--no-sandbox",
          "--disable-web-security",
          "--disable-features=site-per-process",
	  "--user-agent=" + userAgent,
	    }),
	)
	if err := dr.Start(); err != nil {
		fmt.Println(err)
		return
	}
	defer driver.Stop()
	page, err := driver.NewPage()
	if err != nil {
		fmt.Printf("failed to open page, err:%s", err.Error())
		return
	}
	defer page.CloseWindow()
	page.SetPageLoad(10000)
	page.SetScriptTimeout(10000)
startBypass:
	if err := page.Navigate(target); err != nil {
		fmt.Println(err)
	}
	for html, _ := page.HTML(); strings.Contains(html, "__cf_chl_captcha_tk__"); html, _ = page.HTML() {
		if pageurl, err := page.URL(); err == nil {
			answer := strings.Trim(getAnswer(pageurl, userAgent), "\n")
			page.RunScript(`document.getElementsByName("h-captcha-response")[0].value = "` + answer + `"`, nil, nil)
			page.RunScript("document.querySelector('.challenge-form').submit()", nil, nil)```


But to im testing also with your exemple, and get this

```js
(node:12957) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
MoTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
[12998:12998:0318/095624.003914:ERROR:browser_main_loop.cc(1386)] Unable to open X display.
[0318/095624.049374:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/solver/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/root/solver/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:12957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by aw1875** [comment]
@andress134 Never seen this issue before. Try updating your node version and make sure you have all the correct modules installed for the demo. The demo uses:

```bash
npm i puppeteer-extra puppeteer-extra-plugin-stealth
```
And obviously this package as well.

Also, I'm going to assume it has something to do with your OS as you said you're running Debian 9. I'm not sure what puppeteer's limitations are on Debian so I feel like that is the root of this problem.

**Comment by andress134** [comment]
> @andress134 Never seen this issue before. Try updating your node version and make sure you have all the correct modules installed for the demo. The demo uses:
> 
> ```shell
> npm i puppeteer-extra puppeteer-extra-plugin-stealth
> ```
> 
> And obviously this package as well.
> 
> Also, I'm going to assume it has something to do with your OS as you said you're running Debian 9. I'm not sure what puppeteer's limitations are on Debian so I feel like that is the root of this problem.

Problem has from my debian yes, have installed ubuntu and it look working
I still have a question
I have a golang script, that called to hcaptcha solver get answer and return it on my script
I used since with old hcaptcha-solver, now i tried with your but something wrong, idk

Bypass golang function (bypass.go)

```js
dr := agouti.ChromeDriver(
	    agouti.ChromeOptions("args", []string{
	   		"--disable-gpu",
	   		"--no-sandbox",
	   		"--headless",
	   		"--start-maximized",
	   		"--user-agent=" + userAgent,
	    }),
	)
	if err := dr.Start(); err != nil {
		fmt.Println(err)
		return
	}
	defer dr.Stop()
	page, err := dr.NewPage()
	if err != nil {
		fmt.Printf("failed to open page, err:%s", err.Error())
		return
	}
	defer page.CloseWindow()
	page.SetPageLoad(10000)
	page.SetScriptTimeout(10000)
startBypass:
	if err := page.Navigate(website); err != nil {
		fmt.Println(err)
	}
	for html, _ := page.HTML(); strings.Contains(html, "__cf_chl_captcha_tk__"); html, _ = page.HTML() {
		if pageurl, err := page.URL(); err == nil {
			answer := strings.Trim(getAnswer(pageurl, userAgent), "\n")
			page.RunScript(`document.getElementsByName("h-captcha-response")[0].value = "` + answer + `"`, nil, nil)
			page.RunScript("document.querySelector('.challenge-form').submit()", nil, nil)
```

Script that call to hcaptcha repo to get sitekey  (sitekey.js)

```js
const solveCaptcha = require('./hcaptcha-solver/index.js');

(async () => {
    try {
      const response = await solveCaptcha(process.argv[2], base64decode(process.argv[3]));
      console.log(response);
    } catch (error) {
      console.log(error);
    }
})();

function base64decode(base64text){
    return Buffer.from(base64text, 'base64').toString('utf8');
}
````

And script goland that return answer from solver script (sitekey,js) and send it to bypass golang script


```js
package main

import (
	"encoding/base64"
	"fmt"
	"os/exec"
)

func getAnswer(pageurl, userAgent string) string {
	answer, err := exec.Command("node", "sitekey.js", pageurl, base64.StdEncoding.EncodeToString([]byte(userAgent))).Output()
	if err != nil {
		fmt.Println(err)
	}
	return string(answer)
}

````

My question is, how can make it working again using that new hcaptcha-solver updated lib, it is posible?

Sorry for bad my english

**Comment by aw1875** [comment]
@andress134 Honestly don't know much about Go as I've never worked with it unfortunately. Another person is currently working on a GoLang solver based on my module as referenced [here](https://github.com/JimmyLaurent/hcaptcha-solver/issues/13#issuecomment-802518827). If you want you can try and reach out to him to see if you cna work on something together or you can check his progress out [on his repo](https://github.com/JustTalDevelops/hcaptcha-solver-go)

**Comment by JustTalDevelops** [comment]
I might be a bit late, but if you're still on the lookout for a GoLang solver, I made my own implementation based on this repository and completed it just now as @aw1875 mentioned. You can check it out [here if you're interested.](https://github.com/JustTalDevelops/hcaptcha-solver-go)
