### ISSUE TITLE
[Bug]: error when requiring the module

### ISSUE THREAD

**Issue by almadrasa** [aw1875/puppeteer-hcaptcha#44]
**Describe the bug**
hcaptcha is installed but an error fired when i try to require it

**To Reproduce**
```javascript
const { hcaptcha } = require("puppeteer-hcaptcha");
```
- Any other steps needed to reproduce issue.
i'm trying to use this module on glitch (glitch.com) 
node version 12.0.1 and pnpm

**Errors Received**
```
internal/modules/cjs/loader.js:235
      throw err;
      ^
Error: Cannot find module '/rbd/pnpm-volume/8685de08-4417-4a2a-9b34-4cbed7f15400/node_modules/.registry.npmjs.org/puppeteer-hcaptcha/4.1.4/node_modules/ghost-cursor/lib/spoof.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:227:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:364:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:597:27)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/8685de08-4417-4a2a-9b34-4cbed7f15400/node_modules/.registry.npmjs.org/puppeteer-hcaptcha/4.1.4/node_modules/puppeteer-hcaptcha/src/utils.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

**Comment by almadrasa** [comment]
i think it's bcuz of *ghost-cursor*
i tried to require lastest version of *ghost-cursor* and no error was fired

**Comment by aw1875** [comment]
I've never attempted to use the module on glitch. However, the node version does seem very concerning and is probably the issue as node 12 is very far behind. I'm going to close this issue as I don't intend on making any changes to accommodate for glitch or node 12. If you are still having issues on the most recent version of node and not on glitch, please let me know and I can look into that.
