### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Ubnlqs** [aw1875/puppeteer-hcaptcha#48]
Hi
I'm trying demo code

```javascript
const puppeteer = require("puppeteer-extra");
const pluginStealth = require("puppeteer-extra-plugin-stealth");

// Require our hcaptcha method
const { hcaptcha } = require("puppeteer-hcaptcha");

// Tell puppeteer to use puppeteer stealth
puppeteer.use(pluginStealth());

(async () => {
    // Instantiate a new browser object
    // Ignore errors associated to https
    // Can be headless but for example sake we want to show the browser
    // Set your desired arguments for your puppeteer browser
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        headless: false,
        args: [
            `--window-size=600,1000`,
            "--window-position=000,000",
            "--disable-dev-shm-usage",
            "--no-sandbox",
            '--user-data-dir="/tmp/chromium"',
            "--disable-web-security",
            "--disable-features=site-per-process",
        ],
    });

    // Get browser pages
    const [page] = await browser.pages();

    // Send page to your url
    await page.goto("https://2captcha.com/demo/hcaptcha");

    // Remove the page's default timeout function
    await page.setDefaultNavigationTimeout(0);

    // Call hcaptcha method passing in our page
    await hcaptcha(page);

    // Your page is ready to submit.
    // Captcha solving should be the last function on your page so we
    // don't have to worry about the response token expiring.
    /**
     * Example:
     * await page.click("loginDiv > loginBtn");
     */
})();
```
and I got this error

```javascript
C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'objectLocalization')
    at getAnswers (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer-hcaptcha\hcaptcha.js:80:18)
    at tryToSolve (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer-hcaptcha\hcaptcha.js:178:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async solveCaptcha (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer-hcaptcha\hcaptcha.js:255:22)W
    at async Page._onBindingCalled (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:998:28)
    at ExecutionContext._evaluateInternal (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async hcaptcha (C:\Users\Dev\Desktop\project\CaptchaTest\node_modules\puppeteer-hcaptcha\hcaptcha.js:281:17)
    at async gen2 (C:\Users\Dev\Desktop\project\CaptchaTest\index - 10minemail - autosolver.js:39:3)
```
I don't know what's wrong on this code
Sorry for my english

**Comment by Ubnlqs** [comment]
const browser = await puppeteer.launch({args: [
        '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.0 Safari/537.36',  
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-infobars',
        '--window-position=0,0',
        '--lang=en-US,en',
        '--window-size=300,500',
        "--disable-features=site-per-process",
    ],
        headless: false, ignoreHTTPSErrors: true, defaultViewport: {width: 1660, height:1000},
      });

This is my browser properties. 
And the puppeteer user-agent is 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.0 Safari/537.36

**Comment by aw1875** [comment]
The user agent is set within the hcaptcha code. There might be conflicting user agent issues if you're manually setting a user agent yourself when instantiating puppeteer. I'm not entirely sure though as I've never seen or had anyone tell me they've encountered this issue.

**Comment by Ubnlqs** [comment]
So I tried this code
```
// Require puppeteer extra and puppeteer stealth
const puppeteer = require("puppeteer-extra");
const pluginStealth = require("puppeteer-extra-plugin-stealth");

// Require our hcaptcha method
const { hcaptcha } = require("puppeteer-hcaptcha");

// Tell puppeteer to use puppeteer stealth
puppeteer.use(pluginStealth());

(async () => {
  // Instantiate a new browser object
  // Ignore errors associated to https
  // Can be headless but for example sake we want to show the browser
  // Set your desired arguments for your puppeteer browser
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    headless: false,
    args: [
      `--window-size=600,1000`,
      "--window-position=000,000",
      "--disable-dev-shm-usage",
      "--no-sandbox",
      '--user-data-dir="/tmp/chromium"',
      "--disable-web-security",
      "--disable-features=site-per-process",
    ],
  });

  // Get browser pages
  const [page] = await browser.pages();

  // Send page to your url
  await page.goto("https://2captcha.com/demo/hcaptcha");
  await page.waitForTimeout(300)

  // Remove the page's default timeout function
  await page.setDefaultNavigationTimeout(0);

  // Call hcaptcha method passing in our page
  console.log("Start")
  await hcaptcha(page);
  console.log("Stop")

  // Your page is ready to submit.
  // Captcha solving should be the last function on your page so we
  // don't have to worry about the response token expiring.
  /**
   * Example:
   * await page.click("loginDiv > loginBtn");
   */
})();

```
but it return
```
C:\Users\clome\Desktop\Desktop\test>node index.js
Start
C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'objectLocalization')
    at getAnswers (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer-hcaptcha\hcaptcha.js:80:18)
    at tryToSolve (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer-hcaptcha\hcaptcha.js:178:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async solveCaptcha (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer-hcaptcha\hcaptcha.js:255:22)
    at async Page._onBindingCalled (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:998:28)
    at ExecutionContext._evaluateInternal (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async hcaptcha (C:\Users\clome\Desktop\Desktop\test\node_modules\puppeteer-hcaptcha\hcaptcha.js:281:17)
    at async C:\Users\clome\Desktop\Desktop\test\index.js:42:3

C:\Users\clome\Desktop\Desktop\test>
```

**Comment by aw1875** [comment]
Haven't heard anything about this for a few months so will be closing this issue. You can open a new issue if there is anything I can fix on my end.
